# This is a commment.
# Each line is a file pattern followed by one or more owners.

# These owners will be the default owners for erething in
# the repo. Unless a later match takes precedence, 
#  @global-owner1 and global-owner2 will be requested for
# review when someone opends a pull request.

theme: jekyll-theme-hacker
